#!/usr/bin/env python3
"""Validate MCP tool pack against merged catalog and generate unreal-mcp/resources/tools.generated.json."""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from unreal_ai_tool_catalog_merge import load_merged_catalog

REPO_ROOT = Path(__file__).resolve().parents[1]
PACK_PATH = REPO_ROOT / "Plugins" / "UnrealAiEditor" / "Resources" / "mcp" / "mcp-tool-pack.v1.json"
OUT_PATH = REPO_ROOT / "unreal-mcp" / "resources" / "tools.generated.json"
PROMPT_INDEX_PATH = (
    REPO_ROOT / "Plugins" / "UnrealAiEditor" / "prompts" / "mcp" / "06-mcp-tool-pack-index.md"
)


def load_mcp_pack() -> dict:
    return json.loads(PACK_PATH.read_text(encoding="utf-8"))


def validate_pack(pack: dict, merged: dict) -> list[str]:
    errors: list[str] = []
    tools_by_id = {
        t["tool_id"]: t
        for t in merged.get("tools", [])
        if isinstance(t, dict) and isinstance(t.get("tool_id"), str)
    }
    pack_tools = pack.get("tools") or []
    if not isinstance(pack_tools, list) or not pack_tools:
        errors.append("mcp-tool-pack.v1.json: tools[] is empty or missing")
        return errors

    seen: set[str] = set()
    for entry in pack_tools:
        if not isinstance(entry, dict):
            errors.append("pack entry is not an object")
            continue
        tid = entry.get("tool_id")
        if not isinstance(tid, str) or not tid:
            errors.append("pack entry missing tool_id")
            continue
        if tid in seen:
            errors.append(f"duplicate tool_id in pack: {tid}")
        seen.add(tid)

        cat = tools_by_id.get(tid)
        if not cat:
            errors.append(f"tool_id not in merged catalog: {tid}")
            continue
        if "parameters" not in cat or not isinstance(cat["parameters"], dict):
            errors.append(f"catalog missing parameters for: {tid}")
        status = cat.get("status")
        if status in ("future", "designed") and not entry.get("allow_non_implemented"):
            errors.append(f"tool {tid} has status={status} but is in MCP pack without allow_non_implemented")

    return errors


def build_manifest(pack: dict, merged: dict) -> dict:
    tools_by_id = {
        t["tool_id"]: t
        for t in merged.get("tools", [])
        if isinstance(t, dict) and isinstance(t.get("tool_id"), str)
    }
    out_tools = []
    for entry in pack.get("tools", []):
        if not isinstance(entry, dict):
            continue
        tid = entry.get("tool_id")
        if not isinstance(tid, str) or not tid:
            continue
        cat = tools_by_id.get(tid)
        if not cat:
            continue
        out_tools.append(
            {
                "tool_id": tid,
                "summary": cat.get("summary", ""),
                "inputSchema": cat.get("parameters", {"type": "object", "properties": {}}),
                "permission": entry.get("permission") or cat.get("permission"),
                "side_effects": cat.get("side_effects"),
                "status": cat.get("status"),
            }
        )
    return {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "pack_version": pack.get("pack_version", ""),
        "catalog_version_pin": pack.get("catalog_version_pin", ""),
        "tool_count": len(out_tools),
        "tools": out_tools,
    }


def write_prompt_index(pack: dict, manifest: dict) -> None:
    lines = [
        "# Unreal MCP — tool pack index",
        "",
        f"**Pack version:** `{pack.get('pack_version', '')}`  ",
        f"**Catalog pin:** `{pack.get('catalog_version_pin', '')}`  ",
        f"**Tool count:** {manifest['tool_count']}",
        "",
        "_Generated by scripts/generate_mcp_tools.py — do not edit by hand._",
        "",
        "| tool_id | permission | summary |",
        "|---------|------------|---------|",
    ]
    for t in manifest["tools"]:
        summary = (t.get("summary") or "").replace("|", "\\|")
        if len(summary) > 120:
            summary = summary[:117] + "..."
        lines.append(
            f"| `{t['tool_id']}` | {t.get('permission', '')} | {summary} |"
        )
    lines.append("")
    PROMPT_INDEX_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    validate_only = "--validate-only" in sys.argv
    pack = load_mcp_pack()
    merged = load_merged_catalog(REPO_ROOT)
    errors = validate_pack(pack, merged)
    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        return 1

    print(f"MCP pack OK: {len(pack.get('tools', []))} tools validated against merged catalog.")
    if validate_only:
        return 0

    manifest = build_manifest(pack, merged)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_PATH}")
    write_prompt_index(pack, manifest)
    print(f"Wrote {PROMPT_INDEX_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
